language: cpp

os:
  - linux
  - osx

osx_image: osx10.11

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

matrix:
  exclude:
    - os: osx
      compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 'ci/install_linux.sh' ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx"   ]; then 'ci/install_osx.sh'   ; fi

script:
  - python build.py
