# Specify version format
version: "{build}"

# Operating system (build VM template)
os: 
  - Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  - x64

build: false

# specify custom environment variables
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

# scripts that are called at very beginning, before repo cloning
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - cmake --version
  - msbuild /version

# clone directory
clone_folder: C:\projects\conan-dart

# scripts that run after cloning repository
install:
  # Install CONAN 0.4.0
  - cd C:\projects\conan-dart
  - git clone https://github.com/conan-io/conan.git
  - cd conan
  - git fetch
  #- git checkout tags/0.4.0 (disabled since 0.4.0 does not pass the tests)
  - "set PYTHONPATH=%PYTHONPATH%;%CD%"
  - "set CONAN_LOGGING_LEVEL=10"
  - "set CONAN_COMPILER=Visual Studio"
  - "set CONAN_COMPILER_VERSION=12"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install -r requirements_dev.txt"
  - "%PYTHON%/Scripts/pip.exe install -r requirements_server.txt"

test_script:
  # Test CONAN
  - "%PYTHON%/Scripts/nosetests"

  # Test packages
  - ps: cd C:\projects\conan-dart\ci
  - ps: .\appveyor_install.ps1 %APPVEYOR_BUILD_FOLDER%
  - ps: cd C:\projects\conan-dart
  - python build.py

